remote_theme: pmarsceill/just-the-docs
title: Hay Description Specification

# Aux links for the upper right navigation
aux_links:
  "Hay Description Specification on GitHub":
    - "//github.com/fieldgram/hay-description-specification"

# Enable or disable the site search
search_enabled: true

# Set the search token separator for hyphenated-word search:
search_tokenizer_separator: /[\s/]+/

# Enable or disable heading anchors
heading_anchors: true
